"""empty message

Revision ID: 1214d0d9bc00
Revises: d2a6b3c9f35f
Create Date: 2021-09-08 12:48:46.508914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1214d0d9bc00'
down_revision = 'd2a6b3c9f35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
