"""empty message

Revision ID: 302d1ad0a3ec
Revises: 
Create Date: 2021-08-17 12:59:50.238339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302d1ad0a3ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteringpoint',
    sa.Column('gsrn', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('production', 'consumption', name='energydirection'), nullable=False),
    sa.PrimaryKeyConstraint('gsrn'),
    sa.UniqueConstraint('gsrn')
    )
    op.create_index(op.f('ix_meteringpoint_gsrn'), 'meteringpoint', ['gsrn'], unique=False)
    op.create_index(op.f('ix_meteringpoint_sector'), 'meteringpoint', ['sector'], unique=False)
    op.create_index(op.f('ix_meteringpoint_type'), 'meteringpoint', ['type'], unique=False)
    op.create_table('meteringpoint_address',
    sa.Column('gsrn', sa.String(), nullable=False),
    sa.Column('street_code', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('building_number', sa.String(), nullable=True),
    sa.Column('floor_id', sa.String(), nullable=True),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('post_code', sa.String(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('city_sub_division_name', sa.String(), nullable=True),
    sa.Column('municipality_code', sa.String(), nullable=True),
    sa.Column('location_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gsrn'),
    sa.UniqueConstraint('gsrn')
    )
    op.create_index(op.f('ix_meteringpoint_address_gsrn'), 'meteringpoint_address', ['gsrn'], unique=False)
    op.create_table('meteringpoint_technology',
    sa.Column('gsrn', sa.String(), nullable=False),
    sa.Column('tech_code', sa.String(), nullable=True),
    sa.Column('fuel_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gsrn'),
    sa.UniqueConstraint('gsrn')
    )
    op.create_index(op.f('ix_meteringpoint_technology_gsrn'), 'meteringpoint_technology', ['gsrn'], unique=False)
    op.create_table('technology',
    sa.Column('fuel_code', sa.String(), nullable=False),
    sa.Column('tech_code', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('coal', 'nuclear', 'solar', 'wind', name='technologytype'), nullable=True),
    sa.PrimaryKeyConstraint('tech_code', 'fuel_code'),
    sa.UniqueConstraint('tech_code', 'fuel_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technology')
    op.drop_index(op.f('ix_meteringpoint_technology_gsrn'), table_name='meteringpoint_technology')
    op.drop_table('meteringpoint_technology')
    op.drop_index(op.f('ix_meteringpoint_address_gsrn'), table_name='meteringpoint_address')
    op.drop_table('meteringpoint_address')
    op.drop_index(op.f('ix_meteringpoint_type'), table_name='meteringpoint')
    op.drop_index(op.f('ix_meteringpoint_sector'), table_name='meteringpoint')
    op.drop_index(op.f('ix_meteringpoint_gsrn'), table_name='meteringpoint')
    op.drop_table('meteringpoint')
    # ### end Alembic commands ###
