"""empty message

Revision ID: 83274df8603c
Revises: 1214d0d9bc00
Create Date: 2021-10-06 14:13:42.679428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83274df8603c'
down_revision = '1214d0d9bc00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
