"""empty message

Revision ID: d2a6b3c9f35f
Revises: 302d1ad0a3ec
Create Date: 2021-08-23 15:14:08.144207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a6b3c9f35f'
down_revision = '302d1ad0a3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteringpoint_delegate',
    sa.Column('gsrn', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gsrn'),
    sa.UniqueConstraint('gsrn', 'subject')
    )
    op.create_index(op.f('ix_meteringpoint_delegate_gsrn'), 'meteringpoint_delegate', ['gsrn'], unique=False)
    op.create_unique_constraint(None, 'meteringpoint', ['gsrn'])
    op.create_unique_constraint(None, 'meteringpoint_address', ['gsrn'])
    op.create_unique_constraint(None, 'meteringpoint_technology', ['gsrn'])
    op.create_unique_constraint(None, 'technology', ['tech_code', 'fuel_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'technology', type_='unique')
    op.drop_constraint(None, 'meteringpoint_technology', type_='unique')
    op.drop_constraint(None, 'meteringpoint_address', type_='unique')
    op.drop_constraint(None, 'meteringpoint', type_='unique')
    op.drop_index(op.f('ix_meteringpoint_delegate_gsrn'), table_name='meteringpoint_delegate')
    op.drop_table('meteringpoint_delegate')
    # ### end Alembic commands ###
