"""empty message

Revision ID: e691895e95b6
Revises: 83274df8603c
Create Date: 2021-10-06 14:15:02.379838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e691895e95b6'
down_revision = '83274df8603c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meteringpoint', 'sector',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meteringpoint', 'type',
               existing_type=postgresql.ENUM('production', 'consumption', name='energydirection'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meteringpoint', 'type',
               existing_type=postgresql.ENUM('production', 'consumption', name='energydirection'),
               nullable=False)
    op.alter_column('meteringpoint', 'sector',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
