on:
  push:
    branches:
      - main

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Define version
        id: define_version
        run: |
          export MAJOR=0
          export MINOR=0
          export PATCH=${{ github.run_number }}
          export VERSION_NUMBER="V${MAJOR}.${MINOR}.${PATCH}"
          echo $VERSION_NUMBER
          echo "::set-output name=VERSION_NUMBER::$VERSION_NUMBER"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{steps.define_version.outputs.VERSION_NUMBER}}
          release_name: Release ${{steps.define_version.outputs.VERSION_NUMBER}}
          body: ""
          draft: false
          prerelease: false