# --------------- Notes -------------------
# --- Personal Access Token (PAT)
# In order to trigger create a personal token has to be provided instead of GITHUB_TOKEN
# Personal Access token requires following permissions:
# - Access public repositories: repo.public_repo
#
# Remove more at: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token


on:
  push:
    branches:
      - main

name: Create Release

jobs:
  # build:
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
  #     - name: Define version
  #       id: define_version
  #       run: |
  #         export MAJOR=0
  #         export MINOR=0
  #         export PATCH=${{ github.run_number }}
  #         export VERSION_NUMBER="V${MAJOR}.${MINOR}.${PATCH}"
  #         echo $VERSION_NUMBER
  #         echo "::set-output name=VERSION_NUMBER::$VERSION_NUMBER"

  #     - uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0"
  #       with:
  #         repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #         automatic_release_tag: ${{steps.define_version.outputs.VERSION_NUMBER}}
  #         prerelease: false
  #         draft: false
  #         title: Release ${{steps.define_version.outputs.VERSION_NUMBER}}
  
  trigger-update-base-env:
    name: Trigger-Update-Base-Env
    runs-on: ubuntu-latest
    steps:
      - name: Directory update request
        run: |
          [ -z "${{ secrets.ISSUE_PAT }}" ] && echo "Skipping, no ISSUE_PAT" && exit 0
          curl --request POST \
          --url https://api.github.com/repos/RasmusGodske/po-meteringpoints/dispatches \
          --header 'authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "event_type": "repo_updated",
            "client_payload": {
                "repo": "${{ github.repository }}",
                "docker_image_tag": "v.1.2.3"
              }
            }'