name: Create Release V2

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}
  DOCKER_IMAGE: godske/test

  # Url of the current job
  JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  
  # The event which the update_base_env workflow listens to
  UPDATE_BASE_ENV_TRIGGER_EVENT: "update_base_env" 

on:
  push:
    branches:
      - main

jobs:
  CreateRelease:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.define_version.outputs.VERSION_NUMBER }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
      - name: Define version
        id: define_version
        run: |
          export MAJOR=0
          export MINOR=0
          export PATCH=${{ github.run_number }}
          export VERSION_NUMBER="V${MAJOR}.${MINOR}.${PATCH}"
          echo $VERSION_NUMBER
          echo "::set-output name=VERSION_NUMBER::$VERSION_NUMBER"

      - uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0"
        with:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          automatic_release_tag: ${{steps.define_version.outputs.VERSION_NUMBER}}
          prerelease: false
          draft: false
          title: Release ${{ steps.define_version.outputs.VERSION_NUMBER }}
  
  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: CreateRelease
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}},value=v0.0.88
 
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}