name: Update base Env

on:
  # TODO: FOR TESTING - DELETE LATER
  push:
    branches:
      - main
  # repository_dispatch:
  #   types: [update_base_env]
  # workflow_run:
  #   workflows: ["Create Release"]
  #   types:
  #     - completed

env:
  BASE_ENV_REPO: "RasmusGodske/po-base-environment"
  BASE_ENV_REPO_BRANCH: "main"

  DOCKER_IMAGE_VERSION_TAG: "V0.1.2"
  NEW_BRANCH_NAME: "auto_update/po-meteringpoint-updated--${{DOCKER_IMAGE_VERSION_TAG}}"
  

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ env.BASE_ENV_REPO }}
          ref: ${{ env.BASE_ENV_REPO_BRANCH }}
          

      - name: Define version
        run: |
          echo "ls"
      
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "${{ env.NEW_BRANCH_NAME }}"
          git add .
          git commit -m "generated"
          git push origin ${{ env.NEW_BRANCH_NAME }}

      # - name: Get Event payload
      #   id: define_version
      #   run: |
      #     echo "${{ github.event.client_payload.docker_image_tag }}"

      # - name: Checkout code
      #   uses: actions/checkout@v2
      #   with:
      #     token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}