name: Update base Env

on:
  # TODO: FOR TESTING - DELETE LATER
  # push:
  #   branches:
  #     - main
  repository_dispatch:
    types: [update_base_env]


env:
  BASE_ENV_REPO: "RasmusGodske/po-base-environment"
  BASE_ENV_REPO_BRANCH: "main"

  NEW_BRANCH_PREFIK: "auto_update/po-meteringpoint-updated--"
  DOCKER_IMAGE_VERSION_TAG: "V0.1.20"
  CURRENT_JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  # Event payload
  CALLER_REPO: ${{ github.event.client_payload.caller_repo }}
  DOCKER_IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
  CALLER_JOB_URL: ${{ github.event.client_payload.caller_job_url }}

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Get Event payload
        id: event_payload
        run: |
          echo "Caller Repo: ${{ env.CALLER_REPO }}"
          echo "New Docker Tag: ${{ env.DOCKER_IMAGE_TAG }}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ env.BASE_ENV_REPO }}
          ref: ${{ env.BASE_ENV_REPO_BRANCH }}

      - uses: actions/setup-python@v2

      - name: install yaml
        run: python -m pip install pyyaml
 
      - name: Update tags
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import yaml

            file = "yggdrasil/applications/ett/ett-meteringpoints.yaml"
            with open(file) as f:
                doc = yaml.safe_load(f)
                print(doc)

                doc['ett-base-helm-chart']['deployments'][0]['image']['tag'] = "${{ env.DOCKER_IMAGE_VERSION_TAG }}"
                doc['ett-base-helm-chart']['deployments'][1]['image']['tag'] = "${{ env.DOCKER_IMAGE_VERSION_TAG }}"

                with open(file, 'w') as f:
                    yaml.safe_dump(doc, f)

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: Update Meteringpoint Service
          committer: GitHub <noreply@github.com>
          branch: "${{ env.NEW_BRANCH_PREFIK }}${{ env.DOCKER_IMAGE_VERSION_TAG }}"
          body: |
            Update report
            - Updated Meteringpoint Service to version ${{ env.DOCKER_IMAGE_VERSION_TAG }}
            - Auto-generated by [Build][1]
              - Triggered by: ${{ env.CALLER_JOB_URL }}

            [1]: ${{ env.CURRENT_JOB_URL }}

      