name: Update base Env

on:
  repository_dispatch:
    types: [update_base_env]
  # workflow_run:
  #   workflows: ["Create Release"]
  #   types:
  #     - completed
      
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Define version
        id: define_version
        run: |
          echo "${{ github.event.client_payload.repo }}"
          echo "${{ github.event.client_payload.docker_image_tag }}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}