name: Update base Env

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed
      
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Define version
        id: define_version
        run: |
          echo "ran"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}